[user]
username = "agent"
email = "mforoud86@gmail.com"
discord = "Agent Z#7377"

[records]
URL = "https://phazor.ir/"

# hi people who reading this!!
# im agent z. also known as `how much brain do you have` on discord.gg/replit.
# ummm
# idk pronouns?
# she/her
# they/them
# and uhhhh...
# have a great day!
# byeeeeeeee :3
